DROP TABLE CATEGORIA;
DROP TABLE PRODUCTO;

CREATE TABLE PRODUCTO (

ID_PRODUCTO NUMBER NOT NULL,
PRO_NOMBRE VARCHAR2(15) NOT NULL,
PRO_PRECIO NUMBER NOT NULL,
CATEGORIA_ID NUMBER NOT NULL,
CONSTRAINT PRODUCTO_PK PRIMARY KEY(ID_PRODUCTO),
CONSTRAINT PRODUCTO_CATEGORIA_FK FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE CATEGORIA (

ID_CATEGORIA NUMBER NOT NULL,
CAT_NOMBRE VARCHAR2(15) NOT NULL,
CONSTRAINT CATEGORIA_PK PRIMARY KEY (ID_CATEGORIA)

);

INSERT INTO CATEGORIA (ID_CATEGORIA,CAT_NOMBRE)VALUES(SEQ_1.nextval,'LACTEOS');
INSERT INTO PRODUCTO (ID_PRODUCTO,PRO_NOMBRE,PRO_PRECIO,CATEGORIA_ID) VALUES (SEQ_1.nextval,'LECHE CHOCOLATE',900,1);
SELECT * FROM CATEGORIA;
SELECT * FROM PRODUCTO;
CREATE SEQUENCE SEQ_1
START WITH 1
INCREMENT BY 1